#peeper config
peeper:
  zookeepers: localhost:2181
  zookeeper:
    session:
      timeout: 60000

#logger
monitor:
  log:
    home: /data/monitor-log
  collect:
    interval: 6000
  service:
    name: dubbo://dk-monitor:22884
