spring:
  application:
    name: monitor-ui
  profiles:
    active: ui
  mvc:
    view:
      prefix: '/WEB-INF/jsp/'
      suffix: '.jsp'
    contentnegotiation:
      media-types:
        json: application/json

server:
  servlet:
    context-path: '/'
  port: 22880

dubbo:
  application:
    name: ${spring.application.name}
    owner: bieber
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
